<a href="https://colab.research.google.com/github/pankajkumar8709/100-days-of-machine-learning/blob/main/NIRF_Ranking.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import kagglehub
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os

In [2]:
path=kagglehub.dataset_download("nilesh2042/nirf-indian-university-rankings-by-gov-of-india")
path

Downloading to /root/.cache/kagglehub/datasets/nilesh2042/nirf-indian-university-rankings-by-gov-of-india/2.archive...

100%|██████████| 2.75k/2.75k [00:00<00:00, 5.89MB/s]

Extracting files...

'/root/.cache/kagglehub/datasets/nilesh2042/nirf-indian-university-rankings-by-gov-of-india/versions/2'

In [3]:
os.listdir(path)

['Institute_Rankings.csv']

In [4]:
df=pd.read_csv(path+"/Institute_Rankings.csv")

In [5]:
df.sample(5)

,Institute ID,Name,City,State,Score,Rank
6,IR-O-U-0560,Indian Institute of Technology Roorkee,Roorkee,Uttarakhand,71.73,7
69,IR-O-U-0377,Indian Institute of Science Education & Resear...,Mohali,Punjab,52.68,70
52,IR-O-U-0027,Osmania University,Hyderabad,Telangana,55.24,53
48,IR-O-U-0379,Lovely Professional University,Phagwara,Punjab,55.49,49
95,IR-O-U-0217,Christ University,Bengaluru,Karnataka,49.65,96

In [6]:
df.shape

(100, 6)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Institute ID  100 non-null    object
 1   Name          100 non-null    object
 2   City          100 non-null    object
 3   State         100 non-null    object
 4   Score         100 non-null    float64
 5   Rank          100 non-null    int64
dtypes: float64(1), int64(1), object(4)
memory usage: 4.8+ KB

In [8]:
X = df[['City', 'State', 'Score']]
y = df['Rank']

In [11]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

In [13]:
ohe=OneHotEncoder(drop='first',sparse_output=False)
ohe_trf=ohe.fit_transform(X[['City','State']])

In [16]:
ohe.get_feature_names_out()

array(['City_Bengaluru', 'City_Bhopal', 'City_Bhubaneswar',
       'City_Chandigarh', 'City_Chennai', 'City_Cochin',
       'City_Coimbatore', 'City_Dehradun', 'City_Delhi', 'City_Dhanbad',
       'City_Gandhinagar', 'City_Gautam Buddha Nagar',
       'City_Gautam Budh Nagar', 'City_Gorakhpur', 'City_Guwahati',
       'City_Hyderabad', 'City_Indore', 'City_Jaipur', 'City_Jammu',
       'City_Jodhpur', 'City_Kalavakkam', 'City_Kanpur', 'City_Karaikudi',
       'City_Kharagpur', 'City_Khordha', 'City_Kolkata', 'City_Kottayam',
       'City_Kozhikode', 'City_Krishnan Koil', 'City_Lucknow',
       'City_Ludhiana', 'City_Mandi', 'City_Manipal', 'City_Mohali',
       'City_Mohanpur', 'City_Mumbai', 'City_Mysuru', 'City_Nagpur',
       'City_New Delhi', 'City_Patiala', 'City_Patna', 'City_Phagwara',
       'City_Pilani', 'City_Puducherry', 'City_Pune', 'City_Rishikesh',
       'City_Roorkee', 'City_Rourkela', 'City_Rupnagar', 'City_Silchar',
       'City_Srinagar', 'City_Surathkal', 'City_Thanjavur',
       'City_Thiruvananthapuram', 'City_Tiruchirappalli',
       'City_Vaddeswaram', 'City_Varanasi', 'City_Vellore',
       'City_Visakhapatnam', 'City_Warangal', 'City_Wardha',
       'State_Assam', 'State_Bihar', 'State_Chandigarh', 'State_Delhi',
       'State_Gujarat', 'State_Himachal Pradesh',
       'State_Jammu and Kashmir', 'State_Jharkhand', 'State_Karnataka',
       'State_Kerala', 'State_Madhya Pradesh', 'State_Maharashtra',
       'State_Odisha', 'State_Pondicherry', 'State_Punjab',
       'State_Rajasthan', 'State_Tamil Nadu', 'State_Telangana',
       'State_Uttar Pradesh', 'State_Uttarakhand', 'State_West Bengal'],
      dtype=object)

In [18]:
x_trf=pd.DataFrame(ohe_trf,columns=ohe.get_feature_names_out())
x_trf

,City_Bengaluru,City_Bhopal,City_Bhubaneswar,City_Chandigarh,City_Chennai,City_Cochin,City_Coimbatore,City_Dehradun,City_Delhi,City_Dhanbad,...,State_Maharashtra,State_Odisha,State_Pondicherry,State_Punjab,State_Rajasthan,State_Tamil Nadu,State_Telangana,State_Uttar Pradesh,State_Uttarakhand,State_West Bengal
0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
1,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
96,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
97,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
98,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
99,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [21]:
X_trf=np.concatenate((x_trf.values,X[['Score']].values),axis=1)
X_trf

array([[ 0.  ,  0.  ,  0.  , ...,  0.  ,  0.  , 87.31],
       [ 1.  ,  0.  ,  0.  , ...,  0.  ,  0.  , 85.  ],
       [ 0.  ,  0.  ,  0.  , ...,  0.  ,  0.  , 81.62],
       ...,
       [ 0.  ,  0.  ,  0.  , ...,  0.  ,  0.  , 49.38],
       [ 0.  ,  0.  ,  0.  , ...,  0.  ,  0.  , 49.11],
       [ 0.  ,  0.  ,  0.  , ...,  0.  ,  0.  , 49.04]])

In [22]:
y

0       1
1       2
2       3
3       4
4       5
     ...
95     96
96     97
97     98
98     99
99    100
Name: Rank, Length: 100, dtype: int64

In [23]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X_trf,y,test_size=0.2,random_state=2)

In [24]:
lr=LinearRegression()
lr.fit(X_train,y_train)

LinearRegression()

In [25]:
r2_score=lr.score(X_train,y_train)
r2_score

0.947621600893184

In [26]:
from sklearn.ensemble import RandomForestRegressor

In [27]:
rf=RandomForestRegressor()
rf.fit(X_train,y_train)

RandomForestRegressor()

In [28]:
r2_score=rf.score(X_train,y_train)
r2_score

0.9997169801784385

In [29]:
from xgboost import XGBRegressor

In [30]:
xgbr=XGBRegressor()
xgbr.fit(X_train,y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=True, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=None, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=None,
             n_jobs=None, num_parallel_tree=None, ...)

In [31]:
r2_score=xgbr.score(X_train,y_train)
r2_score

0.9999998807907104